# Imagen base ligera
FROM python:3.11-slim

# Crear el usuario no root
RUN useradd -ms /bin/bash django_user

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de requisitos
COPY requirements.txt .

# Instalar las dependencias (sin cache para reducir el tamaño de la imagen)
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación
COPY . .    

# Cambiar permisos
RUN chown -R django_user:django_user /app

# Cambiar al usuario no root
USER django_user

# Exponer el puerto 8000
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["python", "manage.py", "runserver", "0.0.0:8000"]
