version: '3.9'

services:
  db:
    image: postgres16
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "54.32:54.32"
    volumnes:
    - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py runserver &&
             python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: