# Generated by Django 5.2.6 on 2025-09-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='edad',
            new_name='age',
        ),
    ]
