# Generated by Django 5.2.6 on 2025-09-08 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.country'),
        ),
    ]
