# Generated by Django 5.2.6 on 2025-09-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentMethods', to='clients.clients')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typePaymentMethods', to='clients.typepaymentmethod')),
            ],
        ),
    ]
